version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - static:/app/static:ro
      - ./media:/app/media:ro
    restart: always
    ports:
      - '8080:80'
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - POSTGRES_PASSWORD=hackaphone
      - POSTGRES_USER=hackaphone
      - POSTGRES_DB=hackaphone
      - POSTGRES_HOST=db
      - WORKERS=2
      - DEBUG=0
    volumes:
      - static:/app/staticroot:rw
      - ./media:/app/media:rw
    restart: always
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=hackaphone
      - POSTGRES_USER=hackaphone
      - POSTGRES_DB=hackaphone
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  static: {}
