# Generated by Django 3.2 on 2021-12-11 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Номер'),
        ),
    ]
